EnableSequence [
	cset "name='RX1 MIX1 INP1' RX1"
	cset "name='RDAC2 MUX' RX1"
	cset "name='EAR_S' 1"
	# Ver comentario em SpeakerEnableSeq.conf: 'Mute Switch'=on e o
	# default do driver e significa mudo ativo.
	cset "name='RX1 Mute Switch' 0"
]
